quarkus.http.port=8080

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${dbusername}
quarkus.datasource.password=${dbpass}
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/smart_city_reporting

quarkus.hibernate-orm.database.generation=none

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

mp.jwt.verify.issuer=smart-city-reporting
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.new-token.lifespan=43200